Rewrite of zsh config

diff --git a/homedir/zshrc b/homedir/zshrc
--- a/homedir/zshrc
+++ b/homedir/zshrc
@@ -1,9 +1,54 @@
-#Lines configured by zsh-newuser-install
+# Set directory for zinit and plugins
+ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
+
+# Download Zinit, if it's not there yet
+if [ ! -d "$ZINIT_HOME" ]; then
+   mkdir -p "$(dirname $ZINIT_HOME)"
+   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
+fi
+
+# Source/Load zinit
+source "${ZINIT_HOME}/zinit.zsh"
+
+# Enable Oh-My-Posh
+eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/zen.toml)"
+
+# Add in zsh plugins
+zinit light zsh-users/zsh-syntax-highlighting
+zinit light zsh-users/zsh-completions
+zinit light zsh-users/zsh-autosuggestions
+zinit light Aloxaf/fzf-tab
+
+# Add in snippets
+zinit snippet OMZL::git.zsh
+zinit snippet OMZP::git
+zinit snippet OMZP::sudo
+zinit snippet OMZP::archlinux
+zinit snippet OMZP::aws
+zinit snippet OMZP::kubectl
+zinit snippet OMZP::kubectx
+zinit snippet OMZP::command-not-found
+
+# History settings
 HISTFILE=~/.histfile
 HISTSIZE=5000
 SAVEHIST=5000
+HISTDUP=erase
+setopt=appendhistory
+setopt=sharehistory
+setopt=hist_ignore_space
+setopt=hist_ignore_all_dups
+setopt=hist_save_no_dups
+setopt=hist_ignore_dups
+setopt=hist_find_no_dups
 unsetopt beep
-#End of lines configured by zsh-newuser-install
+
+# Completion styling
+zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
+zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
+zstyle ':completion:*' menu no
+zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
+zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'
 
 #The following lines were added by compinstall
 zstyle :compinstall filename ~/.zshrc
@@ -13,78 +58,78 @@ compinit
 #End of lines added by compinstall
 
 #This allows setting menuselect hotkeys
-zmodload zsh/complist
+# zmodload zsh/complist
 
 #This alters the appearance of autocompletion
-zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
-zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
+# zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
+# zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
 
 #This sets the option to ignore duplicate history lines
-setopt HIST_IGNORE_DUPS
+# setopt HIST_IGNORE_DUPS
 
 #Persistant rehash for auto-completion
-setopt nohashdirs
-setopt nohashcmds
+# setopt nohashdirs
+# setopt nohashcmds
 
 # This sets the case insensitivity
-zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
+# zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
 
 #This disables autocomplete of unavailable commands
-zstyle ':completion:*:functions' ignored-patterns '_*'
+# zstyle ':completion:*:functions' ignored-patterns '_*'
 
 #This shows a list of completion options
-zstyle ':completion:*' menu select
+# zstyle ':completion:*' menu select
 
 #This sets the dynamic window title
-termtitle () {
-	case $TERM in
-		xterm*|*rxvt*)
-			print -Pn "\e]0;%n@%m: %~\a"
-			;;
-	esac
-}
+# termtitle () {
+# 	case $TERM in
+# 		xterm*|*rxvt*)
+# 			print -Pn "\e]0;%n@%m: %~\a"
+# 			;;
+# 	esac
+# }
 
-#This sets up the git branch prompt
-setup_git_prompt () {
-	if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-		unset git_prompt
-		return 0
-	fi
-
-	local git_status_dirty git_branch
-
-	if [ "$(git --no-optional-locks status --untracked-files='no' --porcelain)" ]; then
-		git_status_dirty='%F{green}*'
-	else
-		unset git_status_dirty
-	fi
-
-	git_branch="$(git symbolic-ref HEAD 2>/dev/null)"
-	git_branch="${git_branch#refs/heads/}"
-
-	if [ "${#git_branch}" -ge 24 ]; then
-		git_branch="${git_branch:0:21}..."
-	fi
-
-	git_branch="${git_branch:-no branch}"
-
-	git_prompt=" %F{red}[%f${git_branch}${git_status_dirty}%F{red}]%f"
-
-}
-
-precmd () {
-	termtitle
-	setup_git_prompt
-}
-
-#This selects the prompt style and sets an exit status indicator
-setopt promptsubst
-#autoload -U promptinit
-#promptinit
-#prompt redhat
-if [ $SSH_CONNECTION ]; then SSH="%n@%m "; else SSH=""; fi
-PROMPT=%1(j.[%j].)'['$SSH%~']'%(!.#.$)' '
-RPROMPT='${git_prompt}%(?..(%?%))'
+# #This sets up the git branch prompt
+# setup_git_prompt () {
+# 	if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+# 		unset git_prompt
+# 		return 0
+# 	fi
+#
+# 	local git_status_dirty git_branch
+#
+# 	if [ "$(git --no-optional-locks status --untracked-files='no' --porcelain)" ]; then
+# 		git_status_dirty='%F{green}*'
+# 	else
+# 		unset git_status_dirty
+# 	fi
+#
+# 	git_branch="$(git symbolic-ref HEAD 2>/dev/null)"
+# 	git_branch="${git_branch#refs/heads/}"
+#
+# 	if [ "${#git_branch}" -ge 24 ]; then
+# 		git_branch="${git_branch:0:21}..."
+# 	fi
+#
+# 	git_branch="${git_branch:-no branch}"
+#
+# 	git_prompt=" %F{red}[%f${git_branch}${git_status_dirty}%F{red}]%f"
+#
+# }
+#
+# precmd () {
+# 	termtitle
+# 	setup_git_prompt
+# }
+#
+# #This selects the prompt style and sets an exit status indicator
+# setopt promptsubst
+# #autoload -U promptinit
+# #promptinit
+# #prompt redhat
+# if [ $SSH_CONNECTION ]; then SSH="%n@%m "; else SSH=""; fi
+# PROMPT=%1(j.[%j].)'['$SSH%~']'%(!.#.$)' '
+# RPROMPT='${git_prompt}%(?..(%?%))'
 
 #This enables the help command
 autoload -U run-help
@@ -96,16 +141,16 @@ alias help=run-help
 
 # Finally, make sure the terminal is in application mode, when zle is
 # active. Only then are the values from $terminfo valid.
-if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
-	function zle-line-init () {
-		printf '%s' "${terminfo[smkx]}"
-	}
-	function zle-line-finish () {
-		printf '%s' "${terminfo[rmkx]}"
-	}
-	zle -N zle-line-init
-	zle -N zle-line-finish
-fi
+# if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
+# 	function zle-line-init () {
+# 		printf '%s' "${terminfo[smkx]}"
+# 	}
+# 	function zle-line-finish () {
+# 		printf '%s' "${terminfo[rmkx]}"
+# 	}
+# 	zle -N zle-line-init
+# 	zle -N zle-line-finish
+# fi
 
 #This prevents SIGSTOP at Ctrl-S
 #stty -ixon
@@ -133,33 +178,34 @@ setopt correct
 #source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
 
 #This hides gtk3 app messages about not being able to register with accessibility bus
-export NO_AT_BRIDGE=1
+# export NO_AT_BRIDGE=1
 
 #This sets autocomplete for aliases
-setopt no_complete_aliases
+# setopt no_complete_aliases
 
 #This sets default editor to nvim
 export EDITOR=nvim
 
 #Vi bindings
-bindkey -v
-export KEYTIMEOUT=1
+bindkey -e
+# export KEYTIMEOUT=1
 
-bindkey -r "^["
-bindkey "^[[27;2;27~" vi-cmd-mode
+# bindkey -r "^["
+# bindkey "^[[27;2;27~" vi-cmd-mode
 bindkey '^?' backward-delete-char
 bindkey '^H' backward-delete-word
-bindkey '^P' up-history
-bindkey '^N' down-history
+bindkey '^P' history-search-backward
+bindkey '^N' history-search-forward
+bindkey '^y' autosuggest-accept
 
-#Set mode indication in prompt
-function zle-line-init zle-keymap-select {
-    VIM_PROMPT="[% NORMAL]% "
-	RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}${git_prompt}%(?..(%?%)) $EPS1"
-    zle reset-prompt
-}
-zle -N zle-line-init
-zle -N zle-keymap-select
+# #Set mode indication in prompt
+# function zle-line-init zle-keymap-select {
+#     VIM_PROMPT="[% NORMAL]% "
+# 	RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}${git_prompt}%(?..(%?%)) $EPS1"
+#     zle reset-prompt
+# }
+# zle -N zle-line-init
+# zle -N zle-keymap-select
 
 #Aliases
 alias -g L="|less -FX"
@@ -170,7 +216,6 @@ alias ls="eza -s type"
 alias ll="eza -l -s type"
 alias fzf="fzf --height=40% --preview 'bat -n --color=always {}'"
 alias grep="grep --color=auto"
-alias btm="btm -g"
 alias e="$EDITOR"
 alias se="sudoedit"
 alias ..="cd .."
@@ -224,21 +269,6 @@ mkcd ()
 	cd "$1"
 }
 
-ne ()
-{
-	(urxvt -e $EDITOR "$@" &)
-}
-
-nse ()
-{
-	(urxvt -e sudoedit "$@" &)
-}
-
-new ()
-{
-	(urxvt -e "$@" &)
-}
-
 function extract() {
 	if [ -f $1 ] ; then
 		case $1 in
@@ -271,13 +301,13 @@ escape() {
 }
 
 #Prevent nested ranger instances
-ranger() {
-	if [ -z "$RANGER_LEVEL" ]; then
-		/usr/bin/ranger "$@"
-	else
-		exit
-	fi
-}
+# ranger() {
+# 	if [ -z "$RANGER_LEVEL" ]; then
+# 		/usr/bin/ranger "$@"
+# 	else
+# 		exit
+# 	fi
+# }
 
 #Online services
 cs() { curl cheat.sh/$1; }
@@ -306,10 +336,14 @@ key[PageDown]=${terminfo[knp]}
 [[ -n "${key[Down]}"     ]]  && bindkey  "${key[Down]}"     down-line-or-history
 [[ -n "${key[Left]}"     ]]  && bindkey  "${key[Left]}"     backward-char
 [[ -n "${key[Right]}"    ]]  && bindkey  "${key[Right]}"    forward-char
-[[ -n "${key[PageUp]}"   ]]  && bindkey  "${key[PageUp]}"   history-beginning-search-backward
-[[ -n "${key[PageDown]}" ]]  && bindkey  "${key[PageDown]}" history-beginning-search-forward
+[[ -n "${key[PageUp]}"   ]]  && bindkey  "${key[PageUp]}"   history-search-backward
+[[ -n "${key[PageDown]}" ]]  && bindkey  "${key[PageDown]}" history-search-forward
 
-bindkey -M menuselect '^[[Z' reverse-menu-complete
+# bindkey -M menuselect '^[[Z' reverse-menu-complete
 
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
-eval "$(zoxide init zsh)"
+export FZF_CTRL_T_OPTS="
+  --walker-skip .git,node_modules,target
+  --preview 'bat -n --color=always {}'
+  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
+eval "$(zoxide init --cmd cd zsh)"
